In [1]:
import pandas as pd
import numpy as np

In [2]:
movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv")

In [3]:
movies_df

,Unnamed: 0,movieId,title,genres,year
0,0,1,Toy Story,"['Adventure', 'Animation', 'Children', 'Comedy...",1995
1,1,2,Jumanji,"['Adventure', 'Children', 'Fantasy']",1995
2,2,3,Grumpier Old Men,"['Comedy', 'Romance']",1995
3,3,4,Waiting to Exhale,"['Comedy', 'Drama', 'Romance']",1995
4,4,5,Father of the Bride Part II,['Comedy'],1995
...,...,...,...,...,...
61856,62418,209157,We,['Drama'],2018
61857,62419,209159,Window of the Soul,['Documentary'],2001
61858,62420,209163,Bad Poems,"['Comedy', 'Drama']",2018
61859,62421,209169,A Girl Thing,['(no genres listed)'],2001
61860,62422,209171,Women of Devils Island,"['Action', 'Adventure', 'Drama']",1962

In [5]:
movies_df["genres"] = movies_df["genres"].str.split("|")
df_m = movies_df.copy()

In [6]:
genre = pd.DataFrame(columns = ["genre","count"])

In [7]:
list_g = list()
for i in range(len(df_m)):
    for j in range(len(df_m["genres"][i])):
        list_g.append(df_m["genres"][i][j])

In [8]:
g_unique = np.unique(list_g)

In [9]:
for i in range(len(g_unique)):
    genre.loc[i] = [g_unique[i], int(list_g.count(g_unique[i]))]

In [10]:
genre = genre[genre["genre"] != "(no genres listed)"]
genre = genre[genre["genre"] != "IMAX"]

In [11]:
genre = genre.sort_values(by = "count",ascending = False).head(5)

In [12]:
list_cat = genre["genre"].reset_index(drop=True)

In [71]:
list_drama = list()
for i in range(len(movies_df)):
    for j in range(len(movies_df["genres"][i])):
        if(movies_df["genres"][i][j] == list_cat[0]):
            list_drama.append(movies_df["movieId"][i])
list_drama = ratings_df[ratings_df["movieId"].isin(list_drama)]

cnt = list_drama.groupby(by="movieId",as_index= False).count().sort_values(by = "userId", ascending = False)
cnt["vote_num"] = cnt["userId"]
cnt = cnt.drop(columns = "rating")

sum = list_drama.copy()
sum = sum.groupby(by= "movieId",as_index= False).sum()
sum = sum[["movieId","rating"]]

list_drama = sum.merge(cnt,how="left",on= ("movieId"))
list_drama = list_drama.drop(columns= ["timestamp","userId"])

if(list_drama["vote_num"].quantile(0.33) >=2000):
    list_drama = list_drama[list_drama["vote_num"]>list_drama["vote_num"].quantile(0.33)]

else:
    list_drama = list_drama[list_drama["vote_num"]>1999]

list_drama["recommend_rate"] =  list_drama["rating"]/list_drama["vote_num"]
list_drama = list_drama.sort_values(by = "recommend_rate", ascending = False).head(20)
l_m = list_drama["movieId"]

info = movies_df[movies_df['movieId'].isin(l_m)]
list_drama= list_drama.reset_index(drop=True)
list_drama = list_drama.merge(info, how = "left", on = "movieId")
list_drama = list_drama[["movieId","title", "recommend_rate", "vote_num", "genres"]]

In [61]:
list_comedy = list()
for i in range(len(movies_df)):
    for j in range(len(movies_df["genres"][i])):
        if(movies_df["genres"][i][j] == list_cat[1]):
            list_comedy.append(movies_df["movieId"][i])
list_comedy = ratings_df[ratings_df["movieId"].isin(list_comedy)]

cnt = list_comedy.groupby(by="movieId",as_index= False).count().sort_values(by = "userId", ascending = False)
cnt["vote_num"] = cnt["userId"]
cnt = cnt.drop(columns = "rating")
sum = list_comedy.copy()
sum = sum.groupby(by= "movieId",as_index= False).sum()
sum = sum[["movieId","rating"]]
list_comedy = sum.merge(cnt,how="left",on= ("movieId"))
list_comedy = list_comedy.drop(columns= ["timestamp","userId"])

if(list_comedy["vote_num"].quantile(0.33) >=2000):
    list_comedy = list_comedy[list_comedy["vote_num"]>list_comedy["vote_num"].quantile(0.33)]

else:
    list_comedy = list_comedy[list_comedy["vote_num"]>1999]
    
list_comedy["recommend_rate"] =  list_comedy["rating"]/list_comedy["vote_num"]
list_comedy = list_comedy.sort_values(by = "recommend_rate", ascending = False).head(20)
l_m = list_comedy["movieId"]



info = movies_df[movies_df['movieId'].isin(l_m)]
list_comedy= list_comedy.reset_index(drop=True)
list_comedy = list_comedy.merge(info, how = "left", on = "movieId")
list_comedy = list_comedy[["movieId","title", "recommend_rate", "vote_num", "genres"]]

In [62]:
list_thriller = list()
for i in range(len(movies_df)):
    for j in range(len(movies_df["genres"][i])):
        if(movies_df["genres"][i][j] == list_cat[2]):
            list_thriller.append(movies_df["movieId"][i])
list_thriller = ratings_df[ratings_df["movieId"].isin(list_thriller)]

cnt = list_thriller.groupby(by="movieId",as_index= False).count().sort_values(by = "userId", ascending = False)
cnt["vote_num"] = cnt["userId"]
cnt = cnt.drop(columns = "rating")
sum = list_thriller.copy()
sum = sum.groupby(by= "movieId",as_index= False).sum()
sum = sum[["movieId","rating"]]
list_thriller = sum.merge(cnt,how="left",on= ("movieId"))
list_thriller = list_thriller.drop(columns= ["timestamp","userId"])

if(list_thriller["vote_num"].quantile(0.33) >=2000):
    list_thriller = list_thriller[list_thriller["vote_num"]>list_thriller["vote_num"].quantile(0.33)]

else:
    list_thriller = list_thriller[list_thriller["vote_num"]>1999]

list_thriller["recommend_rate"] =  list_thriller["rating"]/list_thriller["vote_num"]
list_thriller = list_thriller.sort_values(by = "recommend_rate", ascending = False).head(20)
l_m = list_thriller["movieId"]

info = movies_df[movies_df['movieId'].isin(l_m)]
list_thriller= list_thriller.reset_index(drop=True)
list_thriller = list_thriller.merge(info, how = "left", on = "movieId")
list_thriller = list_thriller[["movieId","title", "recommend_rate", "vote_num", "genres"]]

In [63]:
list_romance = list()
for i in range(len(movies_df)):
    for j in range(len(movies_df["genres"][i])):
        if(movies_df["genres"][i][j] == list_cat[3]):
            list_romance.append(movies_df["movieId"][i])
list_romance = ratings_df[ratings_df["movieId"].isin(list_romance)]

cnt = list_romance.groupby(by="movieId",as_index= False).count().sort_values(by = "userId", ascending = False)
cnt["vote_num"] = cnt["userId"]
cnt = cnt.drop(columns = "rating")
sum = list_romance.copy()
sum = sum.groupby(by= "movieId",as_index= False).sum()
sum = sum[["movieId","rating"]]
list_romance = sum.merge(cnt,how="left",on= ("movieId"))
list_romance = list_romance.drop(columns= ["timestamp","userId"])

if(list_romance["vote_num"].quantile(0.33) >=2000):
    list_romance = list_romance[list_romance["vote_num"]>list_romance["vote_num"].quantile(0.33)]

else:
    list_romance = list_romance[list_romance["vote_num"]>1999]


list_romance["recommend_rate"] =  list_romance["rating"]/list_romance["vote_num"]
list_romance = list_romance.sort_values(by = "recommend_rate", ascending = False).head(20)
l_m = list_romance["movieId"]

info = movies_df[movies_df['movieId'].isin(l_m)]
list_romance= list_romance.reset_index(drop=True)
list_romance = list_romance.merge(info, how = "left", on = "movieId")
list_romance = list_romance[["movieId","title", "recommend_rate", "vote_num", "genres"]]

In [64]:
list_action = list()
for i in range(len(movies_df)):
    for j in range(len(movies_df["genres"][i])):
        if(movies_df["genres"][i][j] == list_cat[4]):
            list_action.append(movies_df["movieId"][i])
list_action = ratings_df[ratings_df["movieId"].isin(list_action)]

cnt = list_action.groupby(by="movieId",as_index= False).count().sort_values(by = "userId", ascending = False)
cnt["vote_num"] = cnt["userId"]
cnt = cnt.drop(columns = "rating")
sum = list_action.copy()
sum = sum.groupby(by= "movieId",as_index= False).sum()
sum = sum[["movieId","rating"]]
list_action = sum.merge(cnt,how="left",on= ("movieId"))
list_action = list_action.drop(columns= ["timestamp","userId"])

if(list_action["vote_num"].quantile(0.33) >=2000):
    list_action = list_action[list_action["vote_num"]>list_action["vote_num"].quantile(0.33)]

else:
    list_action = list_action[list_action["vote_num"]>2000]

list_action["recommend_rate"] =  list_action["rating"]/list_action["vote_num"]
list_action = list_action.sort_values(by = "recommend_rate", ascending = False).head(20)
l_m = list_action["movieId"]

info = movies_df[movies_df['movieId'].isin(l_m)]
list_action= list_action.reset_index(drop=True)
list_action = list_action.merge(info, how = "left", on = "movieId")
list_action = list_action[["movieId","title", "recommend_rate", "vote_num", "genres"]]

In [72]:
list_drama

,movieId,title,recommend_rate,vote_num,genres
0,318,"Shawshank Redemption, The (1994)",4.413576,81482,"[Crime, Drama]"
1,858,"Godfather, The (1972)",4.324336,52498,"[Crime, Drama]"
2,1221,"Godfather: Part II, The (1974)",4.261759,34188,"[Crime, Drama]"
3,2019,Seven Samurai (Shichinin no samurai) (1954),4.254769,13367,"[Action, Adventure, Drama]"
4,527,Schindler's List (1993),4.247579,60411,"[Drama, War]"
5,1203,12 Angry Men (1957),4.243014,16569,[Drama]
6,2959,Fight Club (1999),4.228311,58773,"[Action, Crime, Drama, Thriller]"
7,1193,One Flew Over the Cuckoo's Nest (1975),4.218662,36058,[Drama]
8,912,Casablanca (1942),4.206564,26890,"[Drama, Romance]"
9,922,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950),4.206501,7368,"[Drama, Film-Noir, Romance]"
10,44555,"Lives of Others, The (Das leben der Anderen) (...",4.200392,9177,"[Drama, Romance, Thriller]"
11,1178,Paths of Glory (1957),4.199342,4254,"[Drama, War]"
12,3435,Double Indemnity (1944),4.194023,5404,"[Crime, Drama, Film-Noir]"
13,296,Pulp Fiction (1994),4.188912,79672,"[Comedy, Crime, Drama, Thriller]"
14,6016,City of God (Cidade de Deus) (2002),4.181587,19894,"[Action, Adventure, Crime, Drama, Thriller]"
15,1213,Goodfellas (1990),4.180525,32663,"[Crime, Drama]"
16,926,All About Eve (1950),4.169692,5068,[Drama]
17,58559,"Dark Knight, The (2008)",4.166538,41519,"[Action, Crime, Drama, IMAX]"
18,79132,Inception (2010),4.155508,38895,"[Action, Crime, Drama, Mystery, Sci-Fi, Thrill..."
19,2324,Life Is Beautiful (La Vita Ã¨ bella) (1997),4.154342,23976,"[Comedy, Drama, Romance, War]"

In [66]:
list_comedy

,movieId,title,recommend_rate,vote_num,genres
0,750,Dr. Strangelove or: How I Learned to Stop Worr...,4.215804,26714,"[Comedy, War]"
1,296,Pulp Fiction (1994),4.188912,79672,"[Comedy, Crime, Drama, Thriller]"
2,2324,Life Is Beautiful (La Vita Ã¨ bella) (1997),4.154342,23976,"[Comedy, Drama, Romance, War]"
3,950,"Thin Man, The (1934)",4.153255,3318,"[Comedy, Crime]"
4,1136,Monty Python and the Holy Grail (1975),4.147655,37723,"[Adventure, Comedy, Fantasy]"
5,1234,"Sting, The (1973)",4.142360,15675,"[Comedy, Crime]"
6,898,"Philadelphia Story, The (1940)",4.137713,6499,"[Comedy, Drama, Romance]"
7,905,It Happened One Night (1934),4.130420,4313,"[Comedy, Romance]"
8,1197,"Princess Bride, The (1987)",4.129097,37863,"[Action, Adventure, Comedy, Fantasy, Romance]"
9,1148,Wallace & Gromit: The Wrong Trousers (1993),4.124787,15270,"[Animation, Children, Comedy, Crime]"
10,92259,Intouchables (2011),4.124755,12745,"[Comedy, Drama]"
11,98491,Paperman (2012),4.115268,2633,"[Animation, Comedy, Romance]"
12,608,Fargo (1996),4.111421,47823,"[Comedy, Crime, Drama, Thriller]"
13,3307,City Lights (1931),4.110568,3170,"[Comedy, Drama, Romance]"
14,3429,Creature Comforts (1989),4.107460,2480,"[Animation, Comedy]"
15,745,Wallace & Gromit: A Close Shave (1995),4.104362,12241,"[Animation, Children, Comedy]"
16,720,Wallace & Gromit: The Best of Aardman Animatio...,4.103381,7719,"[Adventure, Animation, Comedy]"
17,3022,"General, The (1926)",4.101534,2477,"[Comedy, War]"
18,4973,"Amelie (Fabuleux destin d'AmÃ©lie Poulain, Le) ...",4.101282,34320,"[Comedy, Romance]"
19,951,His Girl Friday (1940),4.099156,4145,"[Comedy, Romance]"

In [67]:
list_thriller

,movieId,title,recommend_rate,vote_num,genres
0,50,"Usual Suspects, The (1995)",4.284353,55366,"[Crime, Mystery, Thriller]"
1,904,Rear Window (1954),4.237948,20162,"[Mystery, Thriller]"
2,2959,Fight Club (1999),4.228311,58773,"[Action, Crime, Drama, Thriller]"
3,1212,"Third Man, The (1949)",4.201487,7194,"[Film-Noir, Mystery, Thriller]"
4,44555,"Lives of Others, The (Das leben der Anderen) (...",4.200392,9177,"[Drama, Romance, Thriller]"
5,908,North by Northwest (1959),4.196617,16850,"[Action, Adventure, Mystery, Romance, Thriller]"
6,296,Pulp Fiction (1994),4.188912,79672,"[Comedy, Crime, Drama, Thriller]"
7,6016,City of God (Cidade de Deus) (2002),4.181587,19894,"[Action, Adventure, Crime, Drama, Thriller]"
8,930,Notorious (1946),4.161201,5062,"[Film-Noir, Romance, Thriller]"
9,1260,M (1931),4.160699,4636,"[Crime, Film-Noir, Thriller]"
10,1252,Chinatown (1974),4.158633,16929,"[Crime, Film-Noir, Mystery, Thriller]"
11,79132,Inception (2010),4.155508,38895,"[Action, Crime, Drama, Mystery, Sci-Fi, Thrill..."
12,2571,"Matrix, The (1999)",4.154099,72674,"[Action, Sci-Fi, Thriller]"
13,593,"Silence of the Lambs, The (1991)",4.151342,74127,"[Crime, Horror, Thriller]"
14,4226,Memento (2000),4.149958,41195,"[Mystery, Thriller]"
15,1248,Touch of Evil (1958),4.141198,4823,"[Crime, Film-Noir, Thriller]"
16,48516,"Departed, The (2006)",4.121237,25343,"[Crime, Drama, Thriller]"
17,903,Vertigo (1958),4.120822,15945,"[Drama, Mystery, Romance, Thriller]"
18,2186,Strangers on a Train (1951),4.116548,5457,"[Crime, Drama, Film-Noir, Thriller]"
19,541,Blade Runner (1982),4.115838,36702,"[Action, Sci-Fi, Thriller]"

In [68]:
list_romance

,movieId,title,recommend_rate,vote_num,genres
0,912,Casablanca (1942),4.206564,26890,"[Drama, Romance]"
1,922,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950),4.206501,7368,"[Drama, Film-Noir, Romance]"
2,44555,"Lives of Others, The (Das leben der Anderen) (...",4.200392,9177,"[Drama, Romance, Thriller]"
3,908,North by Northwest (1959),4.196617,16850,"[Action, Adventure, Mystery, Romance, Thriller]"
4,930,Notorious (1946),4.161201,5062,"[Film-Noir, Romance, Thriller]"
5,2324,Life Is Beautiful (La Vita Ã¨ bella) (1997),4.154342,23976,"[Comedy, Drama, Romance, War]"
6,898,"Philadelphia Story, The (1940)",4.137713,6499,"[Comedy, Drama, Romance]"
7,905,It Happened One Night (1934),4.130420,4313,"[Comedy, Romance]"
8,1197,"Princess Bride, The (1987)",4.129097,37863,"[Action, Adventure, Comedy, Fantasy, Romance]"
9,903,Vertigo (1958),4.120822,15945,"[Drama, Mystery, Romance, Thriller]"
10,98491,Paperman (2012),4.115268,2633,"[Animation, Comedy, Romance]"
11,3307,City Lights (1931),4.110568,3170,"[Comedy, Drama, Romance]"
12,1224,Henry V (1989),4.110405,4325,"[Action, Drama, Romance, War]"
13,2858,American Beauty (1999),4.107340,53689,"[Drama, Romance]"
14,4973,"Amelie (Fabuleux destin d'AmÃ©lie Poulain, Le) ...",4.101282,34320,"[Comedy, Romance]"
15,951,His Girl Friday (1940),4.099156,4145,"[Comedy, Romance]"
16,31658,Howl's Moving Castle (Hauru no ugoku shiro) (2...,4.093274,10512,"[Adventure, Animation, Fantasy, Romance]"
17,3462,Modern Times (1936),4.091133,4872,"[Comedy, Drama, Romance]"
18,1704,Good Will Hunting (1997),4.074935,38947,"[Drama, Romance]"
19,928,Rebecca (1940),4.070234,4905,"[Drama, Mystery, Romance, Thriller]"

In [69]:
list_action

,movieId,title,recommend_rate,vote_num,genres
0,2019,Seven Samurai (Shichinin no samurai) (1954),4.254769,13367,"[Action, Adventure, Drama]"
1,2959,Fight Club (1999),4.228311,58773,"[Action, Crime, Drama, Thriller]"
2,908,North by Northwest (1959),4.196617,16850,"[Action, Adventure, Mystery, Romance, Thriller]"
3,6016,City of God (Cidade de Deus) (2002),4.181587,19894,"[Action, Adventure, Crime, Drama, Thriller]"
4,3030,Yojimbo (1961),4.179179,3996,"[Action, Adventure]"
5,58559,"Dark Knight, The (2008)",4.166538,41519,"[Action, Crime, Drama, IMAX]"
6,79132,Inception (2010),4.155508,38895,"[Action, Crime, Drama, Mystery, Sci-Fi, Thrill..."
7,2571,"Matrix, The (1999)",4.154099,72674,"[Action, Sci-Fi, Thriller]"
8,1196,Star Wars: Episode V - The Empire Strikes Back...,4.144122,57361,"[Action, Adventure, Sci-Fi]"
9,3000,Princess Mononoke (Mononoke-hime) (1997),4.138094,13136,"[Action, Adventure, Animation, Drama, Fantasy]"
10,1201,"Good, the Bad and the Ugly, The (Buono, il bru...",4.129336,18162,"[Action, Adventure, Western]"
11,1197,"Princess Bride, The (1987)",4.129097,37863,"[Action, Adventure, Comedy, Fantasy, Romance]"
12,1233,"Boot, Das (Boat, The) (1981)",4.127091,13573,"[Action, Drama, War]"
13,1198,Raiders of the Lost Ark (Indiana Jones and the...,4.123923,54675,"[Action, Adventure]"
14,1254,"Treasure of the Sierra Madre, The (1948)",4.123321,5360,"[Action, Adventure, Drama, Western]"
15,260,Star Wars: Episode IV - A New Hope (1977),4.120189,68717,"[Action, Adventure, Sci-Fi]"
16,541,Blade Runner (1982),4.115838,36702,"[Action, Sci-Fi, Thriller]"
17,1208,Apocalypse Now (1979),4.114714,26370,"[Action, Drama, War]"
18,195159,Spider-Man: Into the Spider-Verse (2018),4.111345,3085,"[Action, Adventure, Animation, Sci-Fi]"
19,1224,Henry V (1989),4.110405,4325,"[Action, Drama, Romance, War]"

In [45]:
list_cat

0       Drama
1      Comedy
2    Thriller
3     Romance
4      Action
Name: genre, dtype: object