In [2]:
import pandas as pd
import numpy as np
import ast
import matplotlib.pyplot as plt
import re
import scipy

In [3]:
movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv")

In [4]:
movies_df

,movieId,title,genres,year
0,1,Toy Story,"['Adventure', 'Animation', 'Children', 'Comedy...",1995
1,2,Jumanji,"['Adventure', 'Children', 'Fantasy']",1995
2,3,Grumpier Old Men,"['Comedy', 'Romance']",1995
3,4,Waiting to Exhale,"['Comedy', 'Drama', 'Romance']",1995
4,5,Father of the Bride Part II,['Comedy'],1995
...,...,...,...,...
61856,209157,We,['Drama'],2018
61857,209159,Window of the Soul,['Documentary'],2001
61858,209163,Bad Poems,"['Comedy', 'Drama']",2018
61859,209169,A Girl Thing,['(no genres listed)'],2001
61860,209171,Women of Devils Island,"['Action', 'Adventure', 'Drama']",1962

In [16]:
limit = (ratings_df["timestamp"].max()) - (7948800)

In [17]:

#Son 3 aydaki filmleri list_m ekle
df = ratings_df[ratings_df['timestamp'] >= limit]
cnt = df.groupby(by="movieId",as_index= False).count().sort_values(by = "userId", ascending = False)
cnt["vote_num"] = cnt["userId"]
cnt = cnt.head(200)
list_m = list(cnt["movieId"])

In [18]:
cnt = cnt[["movieId","vote_num"]]

In [19]:
df = df[df["movieId"].isin(list_m)]

In [20]:
sum = df.copy()
sum = sum.groupby(by= "movieId",as_index= False).sum()
sum = sum[["movieId","rating"]]

In [21]:
df = sum.merge(cnt,how="left",on= ("movieId"))

In [22]:
df["avarage_rating"] = df["rating"]/df["vote_num"]

In [23]:
top12 = df.sort_values(by = "avarage_rating", ascending = False).head(20)
l_m = list(top12["movieId"])

In [24]:
info = movies_df[movies_df['movieId'].isin(l_m)]
top12= top12.reset_index(drop=True)

top12 = top12.merge(info, how = "left", on = "movieId")

top12[["movieId","title", "avarage_rating", "vote_num", "genres"]]

,movieId,title,avarage_rating,vote_num,genres
0,318,"Shawshank Redemption, The (1994)",4.401020,980,Crime|Drama
1,1221,"Godfather: Part II, The (1974)",4.304612,412,Crime|Drama
2,5618,Spirited Away (Sen to Chihiro no kamikakushi) ...,4.299407,506,Adventure|Animation|Fantasy
3,2571,"Matrix, The (1999)",4.291913,1014,Action|Sci-Fi|Thriller
4,858,"Godfather, The (1972)",4.291728,677,Crime|Drama
5,296,Pulp Fiction (1994),4.282500,800,Comedy|Crime|Drama|Thriller
6,1213,Goodfellas (1990),4.266187,417,Crime|Drama
7,27773,Old Boy (2003),4.259804,306,Mystery|Thriller
8,1704,Good Will Hunting (1997),4.252220,563,Drama|Romance
9,58559,"Dark Knight, The (2008)",4.251249,1001,Action|Crime|Drama|IMAX
10,2959,Fight Club (1999),4.241015,946,Action|Crime|Drama|Thriller
11,1193,One Flew Over the Cuckoo's Nest (1975),4.238482,369,Drama
12,47,Seven (a.k.a. Se7en) (1995),4.237805,492,Mystery|Thriller
13,202439,Parasite (2019),4.231935,429,Comedy|Drama
14,109487,Interstellar (2014),4.221027,837,Sci-Fi|IMAX
15,6016,City of God (Cidade de Deus) (2002),4.212733,322,Action|Adventure|Crime|Drama|Thriller
16,112552,Whiplash (2014),4.210076,526,Drama
17,1270,Back to the Future (1985),4.191886,456,Adventure|Comedy|Sci-Fi
18,608,Fargo (1996),4.190418,407,Comedy|Crime|Drama|Thriller
19,293,LÃ©on: The Professional (a.k.a. The Professiona...,4.188917,397,Action|Crime|Drama|Thriller